#!/usr/bin/env bash

waybar &
swaync &
hypridle &
wl-paste --watch cliphist store &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

udiskie &
swayosd-server &
easyeffects --gapplication-service &